### ISSUE TITLE
Automatic builds on push

### ISSUE THREAD

**Issue by fabianmoronzirfas** [technologiestiftung/lab-site#2]
This is for future reference.

Using this settings and shell script we can make an automatic build on push to the repo using https://travis-ci.org until github actions are fully available for public repos (on push event might be enough):  

This is `.travis.yml`
```yml
language: node_js
node_js:
  - "10"
cache:
directories:
  - node_modules
script: npm run build && sh commit-and-push.sh
```

This is `commit-and-push.sh` (might need `chmod +x …`)
The environment variable `$TRAVIS_DEPLOY_TOKEN` needs to be set by a user (could be a user we create `TSBBot` which is useful for automated tasks).
```bash
#!/bin/sh
TODAY=$(date)
git config --global user.email "travis@travis-ci.org"
git config --global user.name "Travis CI"
git config --global push.default current
git stash
git checkout master
git stash pop
git add .
git commit -m "auto-update with travis ${TODAY}"
git push https://${TRAVIS_DEPLOY_TOKEN}@github.com/technologiestiftung/lab-site.git
```
